### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Utilities' of undefined

### ISSUE THREAD

**Issue by Hardell** [winjs/winjs-bower#2]
In ui.js:28.

This is caused because base.js is not imported at all because it's missing in the bower.json

I.e.
"main": ["js/ui.js", "css/ui-dark.css", "fonts/Symbols.ttf"]
in the bower.json should be 
"main": ["js/base.js", "js/ui.js", "css/ui-dark.css", "fonts/Symbols.ttf"]

**Comment by rigdern** [comment]
@Hardell We're having a discussion about this problem and the appropriate fix over in #3. Feel free to head over to #3 and let us know about your particular scenario. Which tool that you are using isn't picking up WinJS's `base.js`?
